version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - docker run -it
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
    env_file:
      - .env
